
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

#permissions:
#  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
        script: |
          cd ..
          cd /home/cleanremove/CleanRemoveServer
          echo "i'm working"

          git pull origin main

          echo ${{ secrets.PASSWORD }} | sudo -kS ./gradlew build

          cd ..

          echo ${{ secrets.PASSWORD }} | sudo -kS nohup java -jar ./CleanRemoveServer/build/libs/cleanremove-0.0.1-SNAPSHOT.jar &
